# Generated by Django 4.1.6 on 2023-02-15 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materails', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, null=True, verbose_name='дата оплаты')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='сумма оплаты')),
                ('pay_type', models.CharField(choices=[('cash', 'наличные'), ('card', 'перевод на счет')], default='cash', max_length=10, verbose_name='способ оплаты')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materails.course', verbose_name='курс')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materails.lesson', verbose_name='урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'оплата',
                'verbose_name_plural': 'оплаты',
            },
        ),
    ]
