# Generated by Django 4.1.6 on 2023-03-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_payment_payment_id_payment_payment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('handle', 'handle'), ('done', 'done'), ('canceled', 'canceled')], default='new', max_length=15),
        ),
    ]
