# Generated by Django 4.1.6 on 2023-03-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materails', '0003_alter_lesson_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='стоимость'),
        ),
    ]
