# Generated by Django 4.1.6 on 2023-03-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materails', '0004_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
